name: "Check Linked Issue"
on:
  pull_request:
    # types: [opened, edited, reopened, synchronize]
    branches:
      - "develop"
      - "main"

jobs:
  check_pull_requests:
    runs-on: ubuntu-latest
    name: Check linked issues
    steps:
      - uses: nearform/github-action-check-linked-issues@v1
        id: check-linked-issues
        with:
          exclude-branches: "release/**, dependabot/**"